blank_issues_enabled: false
contact_links:
  - name: Review the documentation
    url: https://github.com/JuegaTade7175/algol68-vscode-genie-setup
    about: Please review our project README for more details
