blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/JuegaTade7175/algol68-vscode-genie-setup
    about: Read the project README first, it contains many useful details!
